%YAML:1.0

cam0:
  T_cam_imu:
    - [0.9999251540687616, 0.0020459757946525454, -0.012062348179789016, 0.030128183212970606]
    - [-0.0023561263137991586, 0.9996655239172605, -0.02575439690658558, -0.013604985235178281]
    - [0.012005620740144456, 0.02578088971071824, 0.9995955235976035, -0.01314660956348014]
    - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [1]
  camera_model: pinhole
  distortion_coeffs: [0.008034060191085613, -0.00658808382960984, 0.006972249578493765, 0.0011532726940578272]
  distortion_model: radtan
  intrinsics: [429.031869366025, 430.8711499370199, 429.7956310080401, 250.53657120078375]
  resolution: [848, 480]
  rostopic: /camera/camera/infra1/image_rect_raw
  timeshift_cam_imu: 0.002961752093838974
cam1:
  T_cam_imu:
    - [0.9999772309172416, 0.001008066900822623, -0.006672439449648669, -0.06561225537042166]
    - [-0.00118967824717464, 0.9996273864325949, -0.027270367793780517, -0.013823304930341668]
    - [0.00664246285303587, 0.027277684928588203, 0.9996058251091692, -0.013129359457640207]
    - [0.0, 0.0, 0.0, 1.0]
  T_cn_cnm1:
    - [0.9999849344585043, -0.0011764982864882212, 0.005361595639418523, -0.0956855041233061]
    - [0.0011845689030340037, 0.9999981698883537, -0.001502336997929388, -0.00027378414068884594]
    - [-0.005359818330196113, 0.0015086655438741048, 0.9999844980177153, 0.00019905326842100418]
    - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [0]
  camera_model: pinhole
  distortion_coeffs: [0.005272652960048564, -0.003373813851587193, 0.007226318331696024, 7.801477328877106e-05]
  distortion_model: radtan
  intrinsics: [429.36971754503696, 431.33898172542746, 428.41297172851307, 251.2370322980417]
  resolution: [848, 480]
  rostopic: /camera/camera/infra2/image_rect_raw
  timeshift_cam_imu: 0.0029618403249557644
