%YAML:1.0
cam0:
  T_cam_imu:
    - [0.9999618034458498, -0.0016841914455878579, -0.008576429822337115, -0.029225895956825523]
    - [0.001432595484523031, 0.9995708707016929, -0.029257855608989043, -0.028707537602991967]
    - [0.008622025255158382, 0.029244451505086155, 0.9995351033038636, -0.01568285535516504]
    - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: []
  camera_model: pinhole
  distortion_coeffs: [-0.046189606534674306, 0.03780034216978857, 0.010031242717110889, 0.0021373241040323803]
  distortion_model: radtan
  intrinsics: [638.2329765899603, 641.3707072779611, 646.3300714431409, 395.4125547614184]
  resolution: [1280, 720]
  rostopic: /camera/camera/color/image_raw
  timeshift_cam_imu: 0.0009878774192204462
