%YAML:1.0

cam0:
  T_cam_imu:
    - [0.9999251540687616, 0.0020459757946525454, -0.012062348179789016, 0.030128183212970606]
    - [-0.0023561263137991586, 0.9996655239172605, -0.02575439690658558, -0.013604985235178281]
    - [0.012005620740144456, 0.02578088971071824, 0.9995955235976035, -0.01314660956348014]
    - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: []
  camera_model: pinhole
  distortion_coeffs: [0.008034060191085613, -0.00658808382960984, 0.006972249578493765, 0.0011532726940578272]
  distortion_model: radtan
  intrinsics: [429.031869366025, 430.8711499370199, 429.7956310080401, 250.53657120078375]
  resolution: [848, 480]
  rostopic: /camera/camera/infra1/image_rect_raw
  timeshift_cam_imu: 0.002961752093838974
